Soft reset
OpenVPN/easy-rsa pull request #197
Opened 2018-03-05 16:41 UTC by Antagonym

This is similar to what was suggested in #178.

This adds `soft-reset` and `hard-reset` cmd-opts to `init-pki` subcommand, where `hard-reset` recursively removes the PKI directory (the current behavior) and `soft-reset` only removes most of the content, but keeps the directory and the `vars` file (as well as other user created files) intact.

I decided to implement this as cmd-opts instead of a `--option`, because from looking at the existing options, it seems like they are more generic or common to a family of subcommands, whereas cmd-opts seem to be specific to a single subcommand (though `nopass` would be an exception to that rule).

Note that I have made `soft-reset` the default behavior if no cmd-opt is passed, which is different from the previous behavior and may break scripts relying on this. I did this because I find this the saner option in most use-cases, but this can easily be changed if maintaining previous behavior is deemed more important.

2019-03-12 22:10 UTC, SloCompTech commented
@Antagonym looks like sign commit is required, could you push signed commit ? Else please contact one of admins to manually merge tihs feature.

2022-02-09 08:10 UTC, kohlerdominik commented
really waiting for this fix, as it's really necessary for container environments

2022-03-23 21:24 UTC, TinCanTech commented
@Antagonym I'll merge this on the condition that `hard` be default, _current behavior_.

You can either simply agree here, or you can submit a further patch.
I leave the choice in your hands.

2022-03-23 21:26 UTC, TinCanTech requested changes
Please default to `hard`, current behavior.

2022-03-23 21:29 UTC, TinCanTech commented
In truth, I'm not sure `hard` is really required as default because i agree with you.  But for the sake of this work, let's merge it with `hard`, please.

2022-03-31 22:05 UTC, TinCanTech commented
Closed via https://github.com/OpenVPN/easy-rsa/commit/14a29f9fca2128da4a17e478fa04d7ab17d14074

**Default** is set to `hard`

2022-03-31 22:06 UTC, closed without merging